### ISSUE TITLE
URLをPDFのどこかに表示してほしい

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#10]
逸脱判定テスト時、メール内容との紐付けのため、可能であればURLを表示する／しないを選べると良いかと思います。

**Comment by R-Y** [comment]
@kaorinagai 
v0.5.0で対応しました。ご確認をお願いします。
https://github.com/nnh/captosh/releases/tag/v0.5.0

**Comment by R-Y** [comment]
対応済みなのでcloseします。
