### ISSUE TITLE
複数ページを一度にキャプチャーしたい

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#13]
## 背景
Annorated CRF、Blank CRF(FAX)等の出力で下記の操作をしているが面倒
1. シートのページをChrome で開く
2. PDF出力

ファイル名をリストで入力して、次々とキャプチャーを取得する機能が欲しい

## 実装
- ファイル名
  - 現状通りの時間分秒
- ログインをしてから開始を押したらPDFを連続取得
  - 取得するURL一覧を改行区切りのテキストアリアで入力
- 全部終わったら結果画面でテーブルを表示
  - URL
  - 取得結果

**Comment by R-Y** [comment]
de341cd17c26fcf5edfbbe48d664265938dfa1b2
76ea426cb12c0b83afc0317786a2be7dd63bde9e
上記コミットで対応しました。
そのままで良いとのことでmasterにpushしています。

@kaorinagai 
v0.6.0としてアップロードしました。
時間のある時にでもご確認をお願いします。一番右側に追加されたボタンです。
https://github.com/nnh/captosh/releases/tag/v0.6.0

**Comment by R-Y** [comment]
対応済みなのでcloseします。
