### ISSUE TITLE
 複数ページのキャプチャーで、件数が多いとアプリが固まる

### ISSUE THREAD

**Issue by R-Y** [nnh/captosh#15]

**Comment by R-Y** [comment]
https://github.com/nnh/captosh/releases/tag/v0.7.1

@kaorinagai 
対策してみたものを0.7.1でリリースしました。お時間のある時にでもご確認をお願いします。

いっぺんに実行しようとすることでフリーズしていたと思われるので、実行を１つずつ順番に行うようにし、
なおかつ、保存する時の時間が秒の単位まで同じ場合、保存ファイル名が同じになり上書き保存してしまうので、インターバルを１秒取ることにしました。
それゆえ以前より少し時間がかかるようになっています。

**Comment by katsusuke** [comment]
@kaorinagai 本件の確認はその後いかがでしょうか？

**Comment by R-Y** [comment]
@kaorinagai 
私の環境では2000件超えのPDF作成でも落ちませんでした。
お時間のある時にでも確認をお願いします。
https://github.com/nnh/captosh/releases

**Comment by kaorinagai** [comment]
OKです。
