### ISSUE TITLE
ログイン情報を記憶したい

### ISSUE THREAD

**Issue by tosh13** [nnh/captosh#18]

**Comment by katsusuke** [comment]
本件は通常であればブラウザーのCaptosh 側の機能ではなく、ptosh 等対応アプリ側の機能です。
captosh 自体はremember_me 機能に対応しているとこのことです

=> 吉田さんができとうに作ったdevise 入のrails アプリでは動作したとこのとです

その他の意図がありましたでしょうか？（ブラウザーを閉じてもcookie サーバーから送られたcookie 状態を無視して、セッションを保持したい等）

**Comment by R-Y** [comment]
パスワードを保存しておきたい、という問題でしたが、
かなり手間がかかるとのことで一度保留でクローズします。
