### ISSUE TITLE
バリデーション実施時には1つ1つの画面にバリデーション実施者名とバリデーション実施日を表示して欲しい

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#2]
＃背景
-バリデーション時には、1つ1つの画面にバリデーション実施者名とバリデーション実施日が必要

#ストーリー
-1つ1つの画面にバリデーション実施者名とバリデーション実施日を表示して欲しい（バリデーション時の施設権限ログイン者をバリデーション実施者の名前に変更する方法もありますが、日付が出ません）

**Comment by R-Y** [comment]
対応不要なので一度閉じます

**Comment by kaorinagai** [comment]
日付表示はISO8601形式でお願い致します。
位置は画面右上辺りに表示をお願い致します。

https://ja.wikipedia.org/wiki/ISO_8601

**Comment by R-Y** [comment]
@kaorinagai 
表示させたものを0.3.0としてアップロードしました。
お時間のある時にでもご確認をお願いします。

https://github.com/nnh/captosh/releases/tag/v0.3.0

**Comment by R-Y** [comment]
実装したためcloseします
