### ISSUE TITLE
スキーマ/Annotated CRF/ Blank CRFのファイル名に対応したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#21]
## 仕様
captosh:// のリンクを踏んだ時に

URL1,相対パス1\n
URL2,相対パス2\n
...

の様なデータを受け取った場合に相対パスで指定したファイルに保存したい
フォルダーがなければ mkdir -p する
`../`を受け取った時に、出力ディレクトリよりも上に上がらないように気をつける（セキュリティ）
ファイル名として利用できない文字が含まれていたら_ に置換する
ファイル名はユニークな前提ですべて同じフォルダーに出力する

**Comment by katsusuke** [comment]
@R-Y こちらを先に実装お願いしたいです

**Comment by R-Y** [comment]
@katsusuke 
現在の保存位置が
```
（ホームもしくは指定したフォルダ）/ptosh_crf_image/${trialName}/${sheetName}/${datetime}.pdf
```
で保存されているのですが、
```
（ホームもしくは指定したフォルダ）/ptosh_crf_image/相対パス/${datetime}.pdf
```
で保存をするように変更して、
>出力ディレクトリよりも上に上がらないように気をつける

というのはptosh_crf_imageより上に行かない、という解釈でよいのでしょうか？

間違っている場合は具体例をいただけると助かります。

**Comment by katsusuke** [comment]
@R-Y 
> （ホームもしくは指定したフォルダ）/ptosh_crf_image/相対パス/${datetime}.pdf
> で保存をするように変更して、

こちらは違います
例:
```
http://localhost:3000/organizations/BV/trials/BV-HLALCL/cdisc/sheet/registration/annotations,trials/BV-HLALCL/1.症例登録票.pdf
```

という指定を受け取った場合に
相対パス: `trials/BV-HLALCL/1.症例登録票.pdf`
となります

`(ホームもしくは指定したフォルダ)/trials/BV-HLALCL/1.症例登録票.pdf`

に保存してほしいです

> というのはptosh_crf_imageより上に行かない、という解釈でよいのでしょうか？

はいその解釈でOKです

例:

相対パス: `../../../../../../../../ets/hosts`
みたいな文字列を受信した場合
`(ホームもしくは指定したフォルダ)/etc/hosts`
に保存してほしいです
