### ISSUE TITLE
キャプチャー時、どこまで進んでいるのか知りたい

### ISSUE THREAD

**Issue by R-Y** [nnh/captosh#24]
プログレスバーやnow / totalなどで表示する。
保存結果（アドレスと保存先）は不要なので削除する。

**Comment by R-Y** [comment]
@tosh13 
https://github.com/nnh/captosh/releases/tag/v0.10.0
0.10.0に含めました。お時間のある時にでも確認をお願いします。

**Comment by katsusuke** [comment]
@kaorinagai

**Comment by R-Y** [comment]
対応済みなのでcloseします。
問題がある場合はReopenか別issueを立ててくださいますよう、お願いします。
