### ISSUE TITLE
レンダラープロセス側のrequire でカプセル化が破壊されるのを対策したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#25]
https://github.com/nnh/captosh/pull/20#discussion_r240078443

**Comment by katsusuke** [comment]
レンダラープロセス側も babel が動いていると思うのですが、babel でrequire をES的にコンパイルってできないですか？ *1
できないとレンダラープロセス側にWebpackを導入するとか大事な感じになっちゃいますね・・・

> ダイアログ周りをすべてmain.jsに移動して、window.jsとbookmark_event.jsからipcでメッセージを飛ばして、main.js側で処理をするというのは解決になるでしょうか？

プログラミング時にレンダラープロセス側と、メインプロセス側でコーディングスタイルが変わるとバグが入り込みやすくなったり、コードの共通化ができなさそうなのであまりうれしくないです
ですが、require(import) しなくても十分にレンダラープロセス側のコードがシンプルになるのであればそれはそれでありかもしれません

とりあえず *1 を調べてほしいです

**Comment by katsusuke** [comment]
http://karuta-kayituka.hatenablog.com/entry/2018/04/02/200207
webpack で レンダラー/メイン 両方をコンパイルすれば良さそうです

**Comment by R-Y** [comment]
https://github.com/nnh/captosh/releases/tag/v0.12.0
v0.12.0に含めました。

**Comment by R-Y** [comment]
対応済なのでcloseします。
