### ISSUE TITLE
一括キャプチャーの中止ボタンを付けて欲しい。

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#29]
https://www.pivotaltracker.com/story/show/162488510

**Comment by R-Y** [comment]
@tosh13 @kaorinagai 
https://github.com/nnh/captosh/releases/tag/v0.11.0
上記を実装してv0.11.0としてアップロードしました。

**Comment by R-Y** [comment]
対応済みなのでcloseします。
問題がある場合はReopenか別issueを立ててくださいますよう、お願いします。
