### ISSUE TITLE
入力画面をCRF見本として使う場合は、シート名と、シートのfieldの一番上から最後のfieldまでをcaputureしたい。

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#3]
#背景
-入力画面にはシート入力フィールド以外の情報（入力ユーザー情報、登録症例情報、シート作成時施設情報、一時保存やデータセンターに送信等）も表示される
-印刷画面では、フィールドにラベル名を入れていない場合フィールド名が表示されない。
例：CTCAEフィールド
入力画面
http://builder.ptosh.com/organizations/JPLSG/trials/AML-SCT15/sheets/sct100/fax
シート作成画面
http://builder.ptosh.com/organizations/JPLSG/trials/AML-SCT15/sheets/sct100/edit

#ストーリー（Ptoshの方の機能とのことですが念のため記載させていただきます）
入力画面をCRF見本として使う場合は、シート名及び、シートのfield画面だけをcaputureしたい。

**Comment by R-Y** [comment]
対応不要とのことにつき一度閉じます
