### ISSUE TITLE
captosh 側でログインするという仕様が難しいので対策したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#36]
https://www.pivotaltracker.com/story/show/163215458

俊樹先生案
- デフォルトページを googleにする等して、明らかに無関係のブラウザーであることがわかるようにしたい

清水案
- captosh:// リンクを開いた時に、エラーが出たらログインページに飛ばす

**Comment by katsusuke** [comment]
吉田さん案

401/やリダイレクトを受け取ったら「ログインしてください」メッセージを表示

**Comment by katsusuke** [comment]
ログインページを表示する案で実装する

**Comment by R-Y** [comment]
https://github.com/nnh/captosh/releases/tag/v0.12.0

v0.12.0に含めました。お時間のある時にでも確認をお願いします。
@tosh13 @kaorinagai

**Comment by R-Y** [comment]
対応済なのでcloseします。
