### ISSUE TITLE
科・部門マスタ管理画面での施設診療科検索後の画面にてスクリーンショット撮影を行っても何も反応しない。

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#4]
下記科・部門マスタ管理画面での施設診療科検索後の画面にてスクリーンショット撮影を行っても何も反応しない。ファイルも作成されません。
https://review.ptosh.com/master/departments?q=%E5%90%8D%E5%8F%A4%E5%B1%8B%E5%8C%BB%E7%99%82

**Comment by tosh13** [comment]
当然です。eCRFのテストの記録として機能を整備しているので。

**Comment by katsusuke** [comment]
クローズいたします
