### ISSUE TITLE
CSVでファイル名を入力する時にダブルクオートに対応したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/captosh#44]
現在CSV ファイルを開く場合、ダブルクオートが含まれていると正しく動作しない

**Comment by tosh13** [comment]
ダブルクォートをそもそもPtoshからは入らないようにしたい（シート名とかでは使えないようにしたい）です。

**Comment by katsusuke** [comment]
CSV のフォーマットとしてはダブルクオートを含むフォーマットがサポートされているのですが、captosh はCSVを正確にパースしていないため ダブルクオートが入ると動作しません。
ptosh 側から出力するCSVは 原則ダブルクオートで括られているため、captosh にそのまま食わせると動作してくれないです。
