### ISSUE TITLE
フォルダの命名規則を教えてほしい

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#5]
JPLSG ALL-B12シートグループ編集のスクリーンショットがフォルダ名がJPLSGの中のファルダ名「18」の中に保存されています。newというフォルダ名の中には新規オプション作成画面ファイルが保存されています。シート以外の画面についてはどのようにファイルに命名されますか教えてください。

https://review-builder.ptosh.com/organizations/JPLSG/trials/ALL-B12/sheet_groups/18/edit

**Comment by kaorinagai** [comment]
現在のptosh_crf_imageのフォルダ内はこのような感じです。
![default](https://user-images.githubusercontent.com/1088592/27826318-85ba2536-60ed-11e7-82e3-d08615385ecf.PNG)

**Comment by tosh13** [comment]
そもそもCRFのValidationしか対応を考えていません。ファイル名はURLから取ってきています。またreview-builderは新規環境なので、そちらでURLの規則が変わってしまったら対応は出来ません。要望を一つずつ上げていって下さい。現在は「本番環境のeCRFのテスト時の記録作成」の機能をお願いしているので他には対応していません。

**Comment by katsusuke** [comment]
クローズさせて頂きます
