### ISSUE TITLE
Javascript(JS)で非表示設定をしているフィールドがスクリーンショットに表示されてしまう

### ISSUE THREAD

**Issue by kaorinagai** [nnh/captosh#9]
「合併症の有無」がありの場合に合併症の入力欄が開く、なしの場合には合併症の入力欄が開かない設定をしていますが、スクリーンショットではなしの場合で合併症の入力欄が全て表示された状態で保存されています。

ユーザー権限
j-talc2.user@example.com
123456

https://test-ptosh.herokuapp.com/trials/J-TALC2/registrations/kanri-31/sheets/cp/completed_sheets/new

上記シートに下記設定をしている
Javascript(JS)
show_fields_with_radio('field19', ['1'], ['field13','field14','field15','field16','field17','field18','field20','field21','field22','field23','field24','field25'])

Fax、印刷用スタイルシート(SASS)
#field13,#field14, #field15, #field16, #field17, #field18, #field20, #field21,#field22,#field23,#field24,#field25
  display: block !important

**Comment by R-Y** [comment]
@kaorinagai 
v0.4.0で対応しました。
お時間のある時にご確認をお願いします。

https://github.com/nnh/captosh/releases/tag/v0.4.0

**Comment by R-Y** [comment]
対応済みなのでcloseします。
